server:
  port: 8080
spring:
  application.name: password-management
  cloud.config:
    fail-fast: true
    retry.max-attempts: 10
    username: ${CONFIG_SERVER_BA_USERNAME}
    password: ${CONFIG_SERVER_BA_PASSWORD}
  main:
    allow-bean-definition-overriding: true
